import os
import subprocess
import json
from pathlib import Path
from fractions import Fraction

# ==========================================================
# CONFIG
# ==========================================================

VIDEO_DIR     = Path("./videos2")
TEMPLATE_PATH = Path("./template.html")

WEBM_MAX_MB = 1

CTA_HIDE_AT    = 1.7
CTA_SHOW_AGAIN = 8.3

# ==========================================================
# HELPERS
# ==========================================================

def get_duration(video):
    cmd = [
        "ffprobe",
        "-v", "error",
        "-show_entries", "format=duration",
        "-of", "json",
        str(video)
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    data = json.loads(result.stdout)
    return float(data["format"]["duration"])


def get_video_dimensions(video):
    """
    Reads the video's native width/height directly from the file --
    nothing gets cropped or resized to hit a target aspect ratio.
    """
    cmd = [
        "ffprobe",
        "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=width,height",
        "-of", "json",
        str(video)
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    data = json.loads(result.stdout)
    stream = data["streams"][0]
    return int(stream["width"]), int(stream["height"])


def calc_video_bitrate(max_mb, duration):
    """
    Returns bitrate in kbps.
    Reserves ~96 kbps for Opus audio.
    """
    total_bits = max_mb * 8 * 1024 * 1024
    bitrate = (total_bits / duration) / 1000
    bitrate -= 96
    return max(300, int(bitrate))


def even_dims_filter():
    """
    VP9 requires even width/height. This is NOT a crop/aspect change --
    it only rounds an odd dimension down by 1px if the source happens
    to have one. On a normal even-dimensioned source it's a no-op.
    """
    return "scale=trunc(iw/2)*2:trunc(ih/2)*2"


def run_ffmpeg(cmd):
    print("  →", " ".join(cmd))
    subprocess.run(cmd, check=True)


def aspect_ratio_css(width, height):
    """
    Returns the reduced aspect ratio as 'W / H' for use in CSS calc().
    e.g. 1280x720 → '16 / 9', 720x1280 → '9 / 16', 720x960 → '3 / 4'
    """
    f = Fraction(width, height)
    return f"{f.numerator} / {f.denominator}"


def get_orientation(width, height):
    """
    Drives which CTA layout the template uses ('landscape' vs 'portrait'),
    derived from the video's own native dimensions.
    """
    return "landscape" if width >= height else "portrait"


def load_template():
    """
    Loads the ad template once from disk. The template is the exact
    ad markup/CSS/JS, with @@PLACEHOLDER@@ tokens standing in for the
    handful of values that change per video.
    """
    if not TEMPLATE_PATH.exists():
        raise FileNotFoundError(
            f"Template not found at {TEMPLATE_PATH}. "
            "Put the ad template (template.html) next to this script."
        )
    return TEMPLATE_PATH.read_text(encoding="utf-8")


def write_html(html_path, template, webm_filename, width, height, title):
    """
    Copies the template HTML and substitutes the per-creative values
    (native dimensions, aspect ratio, orientation, video filename,
    title, CTA timings) via plain string replacement. No HTML is
    rebuilt/generated by hand -- the template file is the single
    source of truth for markup/CSS/JS. The template itself branches
    its CTA layout off @@ORIENTATION@@ (landscape = mid-right
    placement, portrait = bottom-center placement).
    """

    w_over_h    = aspect_ratio_css(width, height)
    h_over_w    = aspect_ratio_css(height, width)
    orientation = get_orientation(width, height)

    replacements = {
        "@@WIDTH@@":          str(width),
        "@@HEIGHT@@":         str(height),
        "@@TITLE@@":          title,
        "@@WEBM_FILENAME@@":  webm_filename,
        "@@W_OVER_H@@":       w_over_h,
        "@@H_OVER_W@@":       h_over_w,
        "@@ORIENTATION@@":    orientation,
        "@@CTA_HIDE_AT@@":    str(CTA_HIDE_AT),
        "@@CTA_SHOW_AGAIN@@": str(CTA_SHOW_AGAIN),
    }

    html = template
    for placeholder, value in replacements.items():
        html = html.replace(placeholder, value)

    html_path.write_text(html, encoding="utf-8")


# ==========================================================
# MAIN
# ==========================================================

template = load_template()

videos = list(VIDEO_DIR.glob("*.mp4"))

if not videos:
    print("No MP4 files found in ./videos/")
    exit()

for video in videos:
    print(f"\n{'='*60}")
    print(f"  Processing: {video.name}")
    print(f"{'='*60}")

    duration   = get_duration(video)
    width, height = get_video_dimensions(video)
    base       = video.stem   # e.g. "video1"

    print(f"\n  Native size: {width}×{height}  (no cropping/aspect change)")

    # Output folder: videos/video1/
    out_dir = VIDEO_DIR / base
    out_dir.mkdir(parents=True, exist_ok=True)

    webm_name = f"{base}.webm"
    webm_out  = out_dir / webm_name

    # ------------------------------------------------------
    # WebM — VP9 + Opus, native dimensions, no crop/scale
    # ------------------------------------------------------
    webm_bitrate = calc_video_bitrate(WEBM_MAX_MB, duration)

    webm_cmd = [
        "ffmpeg",
        "-y",
        "-i", str(video),

        "-vf", even_dims_filter(),

        "-c:v", "libvpx-vp9",
        "-b:v", f"{webm_bitrate}k",
        "-crf", "35",

        "-c:a", "libopus",
        "-b:a", "96k",

        str(webm_out)
    ]

    run_ffmpeg(webm_cmd)

    # ------------------------------------------------------
    # index.html — copied from template.html, values substituted
    # ------------------------------------------------------
    html_out = out_dir / "index.html"
    write_html(
        html_path=html_out,
        template=template,
        webm_filename=webm_name,
        width=width,
        height=height,
        title=base,
    )

    print(f"  ✓  {out_dir}/")
    print(f"       ├── index.html")
    print(f"       └── {webm_name}")

print("\n\nAll videos processed successfully.")
print("\nOutput structure:")
print("  videos/")
for video in videos:
    base = video.stem
    print(f"  └── {base}/")
    print(f"        ├── index.html")
    print(f"        └── {base}.webm")